CREATE USER surfapp;
CREATE DATABASE surfing OWNER surfapp;

CREATE TABLE SURF_BREAK(ID SERIAL PRIMARY KEY,NAME CHAR(64));
CREATE TABLE SURF_TYPE(ID SERIAL PRIMARY KEY, SURF_TYPE CHAR(32), CODE CHAR(16));

ALTER TABLE SURF_BREAK ADD SURF_TYPE_ID integer;

alter table SURF_BREAK add constraint fk_surf_break_type foreign key (SURF_TYPE_ID) REFERENCES SURF_TYPE (id);